import { ClassicalProofReference, YogaCategory, DoshaCategory } from '../types/yogaDoshaTypes';

export interface YogaRuleDefinition {
  ruleCode: string;
  nameNepali: string;
  nameSanskrit: string;
  category: YogaCategory;
  descriptionNepali: string;
  classicalProof: ClassicalProofReference;
  requiredPlanets: string[];
  priorityScore: number;
}

export interface DoshaRuleDefinition {
  ruleCode: string;
  nameNepali: string;
  nameSanskrit: string;
  category: DoshaCategory;
  descriptionNepali: string;
  classicalProof: ClassicalProofReference;
  cancellationRulesSummaryNepali: string[];
  remediesNepali: string[];
}

export const YOGA_RULE_REGISTRY: YogaRuleDefinition[] = [
  {
    ruleCode: 'YOGA_RAJAYOGA_KENDRA_TRIKONA',
    nameNepali: 'केन्द्र–त्रिकोण राजयोग (धर्मकर्माधिपति)',
    nameSanskrit: 'केन्द्रत्रिकोणराजयोगः',
    category: 'राजयोग',
    descriptionNepali: 'केन्द्र भाव (१, ४, ७, १०) का स्वामी र त्रिकोण भाव (१, ५, ९) का स्वामी बीच युति, दृष्टि वा राशि परिवर्तन हुनु।',
    classicalProof: {
      textNameNepali: 'बृहत्पाराशर होराशास्त्र',
      textNameSanskrit: 'बृहत्पाराशरहोराशास्त्रम्',
      chapter: 'अध्याय ३५ (राजयोगाध्याय)',
      shlokaOrVerse: 'श्लोक १–५',
      originalSanskritText: 'केन्द्रत्रिकोणपतयः सम्बन्धेन परस्परम्। राजयोगं प्रकुर्वन्ति प्रसिद्धं सर्वसम्मतम्॥',
      nepaliMeaningSummary: 'केन्द्र र त्रिकोणका स्वामीहरू आपसमा सम्बद्ध हुँदा श्रेष्ठ राजयोग निर्माण हुन्छ, जसले उच्च अधिकार, पद र प्रतिष्ठा प्रदान गर्दछ।',
    },
    requiredPlanets: [],
    priorityScore: 100,
  },
  {
    ruleCode: 'YOGA_DHANAYOGA_2_5_9_11',
    nameNepali: 'महाधन योग (द्वितीय, पञ्चम, नवम, एकादश सम्बन्धी)',
    nameSanskrit: 'महाधनयोगः',
    category: 'धनयोग',
    descriptionNepali: 'धन भाव (२), पञ्चम भाव (५), भाग्य भाव (९) र लाभ भाव (११) का स्वामीहरू बीच युति वा सम्बन्ध हुनु।',
    classicalProof: {
      textNameNepali: 'फलदीपिका',
      textNameSanskrit: 'फलदीपिका',
      chapter: 'अध्याय ६ (योगाध्याय)',
      shlokaOrVerse: 'श्लोक २६–२८',
      nepaliMeaningSummary: 'धनेश, लाभेश र भाग्येश एकापसमा सम्बद्ध हुँदा धनको प्रचुर आगमन, स्थिर सम्पत्ति र वैभव प्राप्त हुन्छ।',
    },
    requiredPlanets: [],
    priorityScore: 90,
  },
  {
    ruleCode: 'YOGA_VIPAREETA_HARSHA',
    nameNepali: 'हर्ष विपरीत राजयोग',
    nameSanskrit: 'हर्षविपरीतराजयोगः',
    category: 'विपरीत राजयोग',
    descriptionNepali: 'षष्ठेश (६ औँ भावको स्वामी) ६ औँ, ८ औँ वा १२ औँ भावमा स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'उत्तरकालामृत',
      textNameSanskrit: 'उत्तरकालामृतम्',
      chapter: 'अध्याय ४',
      shlokaOrVerse: 'श्लोक २२',
      nepaliMeaningSummary: 'छैटौँ भावको स्वामी त्रिक (६, ८, १२) भावमा बस्दा शत्रु विजय, रोगमुक्ति र अचानक सफलता मिल्दछ।',
    },
    requiredPlanets: [],
    priorityScore: 85,
  },
  {
    ruleCode: 'YOGA_VIPAREETA_SARALA',
    nameNepali: 'सरल विपरीत राजयोग',
    nameSanskrit: 'सरलविपरीतराजयोगः',
    category: 'विपरीत राजयोग',
    descriptionNepali: 'अष्टमेश (८ औँ भावको स्वामी) ६ औँ, ८ औँ वा १२ औँ भावमा स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'उत्तरकालामृत',
      textNameSanskrit: 'उत्तरकालामृतम्',
      chapter: 'अध्याय ४',
      shlokaOrVerse: 'श्लोक २२',
      nepaliMeaningSummary: 'आठौँ भावको स्वामी त्रिक भावमा बस्दा दीर्घायु, विद्वता, गुप्त धन र विषम परिस्थितिमा विजय मिल्दछ।',
    },
    requiredPlanets: [],
    priorityScore: 85,
  },
  {
    ruleCode: 'YOGA_VIPAREETA_VIMALA',
    nameNepali: 'विमल विपरीत राजयोग',
    nameSanskrit: 'विमलविपरीतराजयोगः',
    category: 'विपरीत राजयोग',
    descriptionNepali: 'द्वादशेश (१२ औँ भावको स्वामी) ६ औँ, ८ औँ वा १२ औँ भावमा स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'उत्तरकालामृत',
      textNameSanskrit: 'उत्तरकालामृतम्',
      chapter: 'अध्याय ४',
      shlokaOrVerse: 'श्लोक २३',
      nepaliMeaningSummary: 'बारहौँ भावको स्वामी त्रिक भावमा बस्दा कम खर्च, स्वाभिमानी जीवन र विदेश सफलता प्राप्त हुन्छ।',
    },
    requiredPlanets: [],
    priorityScore: 85,
  },
  {
    ruleCode: 'YOGA_RUCHAKA_MAHAPURUSHA',
    nameNepali: 'रुचक महापुरुष योग',
    nameSanskrit: 'रुचकपञ्चमहापुरुषयोगः',
    category: 'पंचमहापुरुष',
    descriptionNepali: 'मंगल ग्रह लग्नबाट केन्द्र भाव (१, ४, ७, १०) मा स्वक्षेत्र (मेष/वृश्चिक) वा उच्च राशि (मकर) मा स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'बृहत्पाराशर होराशास्त्र',
      textNameSanskrit: 'बृहत्पाराशरहोराशास्त्रम्',
      chapter: 'अध्याय ७५ (महापुरुषयोगाध्याय)',
      shlokaOrVerse: 'श्लोक १–४',
      nepaliMeaningSummary: 'रुचक योगमा जन्मने व्यक्ति साहसी, सेना/प्रशासन प्रमुख, पराक्रमी र तेजस्वी हुन्छ।',
    },
    requiredPlanets: ['मंगल'],
    priorityScore: 95,
  },
  {
    ruleCode: 'YOGA_BHADRA_MAHAPURUSHA',
    nameNepali: 'भद्र महापुरुष योग',
    nameSanskrit: 'भद्रपञ्चमहापुरुषयोगः',
    category: 'पंचमहापुरुष',
    descriptionNepali: 'बुध ग्रह लग्नबाट केन्द्र भाव (१, ४, ७, १०) मा स्वक्षेत्र (मिथुन) वा उच्च राशि (कन्या) मा स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'जातकपारिजात',
      textNameSanskrit: 'जातकपारिजातः',
      chapter: 'अध्याय ६',
      shlokaOrVerse: 'श्लोक ५६',
      nepaliMeaningSummary: 'भद्र योगले वाक्पटुता, महान् बौद्धिकता, व्यापारिक सफलता र दीर्घायु दिन्छ।',
    },
    requiredPlanets: ['बुध'],
    priorityScore: 95,
  },
  {
    ruleCode: 'YOGA_HAMSA_MAHAPURUSHA',
    nameNepali: 'हंस महापुरुष योग',
    nameSanskrit: 'हंसपञ्चमहापुरुषयोगः',
    category: 'पंचमहापुरुष',
    descriptionNepali: 'गुरु ग्रह लग्नबाट केन्द्र भाव (१, ४, ७, १०) मा स्वक्षेत्र (धनु/मीन) वा उच्च राशि (कर्कट) मा स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'बृहत्पाराशर होराशास्त्र',
      textNameSanskrit: 'बृहत्पाराशरहोराशास्त्रम्',
      chapter: 'अध्याय ७५',
      shlokaOrVerse: 'श्लोक ७–८',
      nepaliMeaningSummary: 'हंस योगले सर्वत्र पूज्यता, उच्च ज्ञान, धार्मिक निष्ठा र राजमान्य व्यक्तित्व प्रदान गर्दछ।',
    },
    requiredPlanets: ['गुरु'],
    priorityScore: 95,
  },
  {
    ruleCode: 'YOGA_MALAVYA_MAHAPURUSHA',
    nameNepali: 'मालव्य महापुरुष योग',
    nameSanskrit: 'मालव्यपञ्चमहापुरुषयोगः',
    category: 'पंचमहापुरुष',
    descriptionNepali: 'शुक्र ग्रह लग्नबाट केन्द्र भाव (१, ४, ७, १०) मा स्वक्षेत्र (वृष/तुला) वा उच्च राशि (मीन) मा स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'सारवली',
      textNameSanskrit: 'सारावली',
      chapter: 'अध्याय ३७',
      shlokaOrVerse: 'श्लोक ९',
      nepaliMeaningSummary: 'मालव्य योगले वाहन सुख, सौन्दर्य, कला, वैभव र दाम्पत्य आनन्द प्रदान गर्दछ।',
    },
    requiredPlanets: ['शुक्र'],
    priorityScore: 95,
  },
  {
    ruleCode: 'YOGA_SASA_MAHAPURUSHA',
    nameNepali: 'शश महापुरुष योग',
    nameSanskrit: 'शशपञ्चमहापुरुषयोगः',
    category: 'पंचमहापुरुष',
    descriptionNepali: 'शनि ग्रह लग्नबाट केन्द्र भाव (१, ४, ७, १०) मा स्वक्षेत्र (मकर/कुम्भ) वा उच्च राशि (तुला) मा स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'बृहत्पाराशर होराशास्त्र',
      textNameSanskrit: 'बृहत्पाराशरहोराशास्त्रम्',
      chapter: 'अध्याय ७५',
      shlokaOrVerse: 'श्लोक ११–१२',
      nepaliMeaningSummary: 'शश योगमा जन्मेको व्यक्ति लोकनायक, न्यायप्रिय, रणनीतिकार र विशाल जनसमुदायको नेता हुन्छ।',
    },
    requiredPlanets: ['शनि'],
    priorityScore: 95,
  },
  {
    ruleCode: 'YOGA_NEECHABHANGA_RAJAYOGA',
    nameNepali: 'नीचभङ्ग राजयोग',
    nameSanskrit: 'नीचभङ्गराजयोगः',
    category: 'विपरीत राजयोग',
    descriptionNepali: 'नीच स्थितिमा रहेको ग्रहको राशि स्वामी वा उच्च राशि स्वामी लग्न वा चन्द्रमाबाट केन्द्रमा रहनु वा नीच ग्रह स्वयम् दृष्ट हुनु।',
    classicalProof: {
      textNameNepali: 'फलदीपिका',
      textNameSanskrit: 'फलदीपिका',
      chapter: 'अध्याय ६',
      shlokaOrVerse: 'श्लोक २६–३०',
      nepaliMeaningSummary: 'नीच ग्रहको नीचता भङ्ग हुँदा सुरुमा संघर्ष भए पनि पछि सम्राट सरहको उच्च पद र सफलता प्राप्त हुन्छ।',
    },
    requiredPlanets: [],
    priorityScore: 88,
  },
  {
    ruleCode: 'YOGA_GAJAKESARI',
    nameNepali: 'गजकेसरी योग',
    nameSanskrit: 'गजकेसरीयोगः',
    category: 'राजयोग',
    descriptionNepali: 'चन्द्रमाबाट देवगुरु बृहस्पति १, ४, ७, १० औँ केन्द्र भावमा रहनु र गुरु अस्त वा नीच नहुनु।',
    classicalProof: {
      textNameNepali: 'जातकपारिजात',
      textNameSanskrit: 'जातकपारिजातः',
      chapter: 'अध्याय ७',
      shlokaOrVerse: 'श्लोक १४',
      originalSanskritText: 'केन्द्रे गुरुः शशिसुतात् यदि केसरी स्यात्।',
      nepaliMeaningSummary: 'गजकेसरी योगले हात्ती र सिंह सरहको पराक्रम, अखण्ड यश, लोकप्रियता र प्रचुर धन दिन्छ।',
    },
    requiredPlanets: ['गुरु', 'चन्द्र'],
    priorityScore: 92,
  },
  {
    ruleCode: 'YOGA_BUDHADITYA',
    nameNepali: 'बुधादित्य योग',
    nameSanskrit: 'बुधादित्ययोगः',
    category: 'सूर्य योग',
    descriptionNepali: 'सूर्य र बुध एउटै भावमा स्थित हुनु तथा बुध अत्यधिक अस्त (३ अंश भन्दा नजिक) नहुनु।',
    classicalProof: {
      textNameNepali: 'बृहत्पाराशर होराशास्त्र',
      textNameSanskrit: 'बृहत्पाराशरहोराशास्त्रम्',
      chapter: 'अध्याय ३५',
      shlokaOrVerse: 'श्लोक १२',
      nepaliMeaningSummary: 'सूर्य र बुधको संयोजनले तीव्र तार्किक बुद्धि, गणितीय निपुणता, सरकारी मानसम्मान र कुशल अभिव्यक्ति दिन्छ।',
    },
    requiredPlanets: ['सूर्य', 'बुध'],
    priorityScore: 80,
  },
  {
    ruleCode: 'YOGA_VESI',
    nameNepali: 'वेशि योग',
    nameSanskrit: 'वेशियोगः',
    category: 'सूर्य योग',
    descriptionNepali: 'सूर्य रहेको राशिबाट दोस्रो (२ औँ) भावमा राहु-केतु बाहेक शुभ वा अन्य ग्रह हुनु।',
    classicalProof: {
      textNameNepali: 'बृहज्जातक',
      textNameSanskrit: 'बृहज्जातकम्',
      chapter: 'अध्याय १३',
      shlokaOrVerse: 'श्लोक १',
      nepaliMeaningSummary: 'वेशि योगले व्यक्तिलाई सत्यवादी, सुन्दर, सुखी र स्थिर समृद्धशाली बनाउँछ।',
    },
    requiredPlanets: ['सूर्य'],
    priorityScore: 75,
  },
  {
    ruleCode: 'YOGA_VASI',
    nameNepali: 'वासि योग',
    nameSanskrit: 'वासियोगः',
    category: 'सूर्य योग',
    descriptionNepali: 'सूर्य रहेको राशिबाट बाह्रौँ (१२ औँ) भावमा राहु-केतु बाहेक शुभ वा अन्य ग्रह हुनु।',
    classicalProof: {
      textNameNepali: 'बृहज्जातक',
      textNameSanskrit: 'बृहज्जातकम्',
      chapter: 'अध्याय १३',
      shlokaOrVerse: 'श्लोक २',
      nepaliMeaningSummary: 'वासि योगले विद्या, साहस, राजमान्यता र प्रसिद्ध वाक्शक्ति दिन्छ।',
    },
    requiredPlanets: ['सूर्य'],
    priorityScore: 75,
  },
  {
    ruleCode: 'YOGA_UBHAYACHARI',
    nameNepali: 'उभयचरी योग',
    nameSanskrit: 'उभयचरीयोगः',
    category: 'सूर्य योग',
    descriptionNepali: 'सूर्यबाट २ औँ र १२ औँ दुवै भावमा ग्रहहरू स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'सारवली',
      textNameSanskrit: 'सारावली',
      chapter: 'अध्याय १३',
      shlokaOrVerse: 'श्लोक ८',
      nepaliMeaningSummary: 'उभयचरी योगले राजा सरहको सुख, राजकीय सम्मान, धैर्य र उदार चित्त दिन्छ।',
    },
    requiredPlanets: ['सूर्य'],
    priorityScore: 82,
  },
  {
    ruleCode: 'YOGA_SUNAPHA',
    nameNepali: 'सुनफा योग',
    nameSanskrit: 'सुनफायोगः',
    category: 'चन्द्र योग',
    descriptionNepali: 'चन्द्रमाबाट दोस्रो (२ औँ) भावमा सूर्य, राहु, केतु बाहेक अन्य ग्रह हुनु।',
    classicalProof: {
      textNameNepali: 'बृहत्पाराशर होराशास्त्र',
      textNameSanskrit: 'बृहत्पाराशरहोराशास्त्रम्',
      chapter: 'अध्याय ३७',
      shlokaOrVerse: 'श्लोक २–४',
      nepaliMeaningSummary: 'सुनफा योगले स्वआर्जित धन, बुद्धिमत्ता र राजकीय अधिकार दिन्छ।',
    },
    requiredPlanets: ['चन्द्र'],
    priorityScore: 78,
  },
  {
    ruleCode: 'YOGA_ANAPHA',
    nameNepali: 'अनफा योग',
    nameSanskrit: 'अनफायोगः',
    category: 'चन्द्र योग',
    descriptionNepali: 'चन्द्रमाबाट बाह्रौँ (१२ औँ) भावमा सूर्य, राहु, केतु बाहेक अन्य ग्रह हुनु।',
    classicalProof: {
      textNameNepali: 'बृहत्पाराशर होराशास्त्र',
      textNameSanskrit: 'बृहत्पाराशरहोराशास्त्रम्',
      chapter: 'अध्याय ३७',
      shlokaOrVerse: 'श्लोक ५–७',
      nepaliMeaningSummary: 'अनफा योगले निरोगी शरीर, सदाचार, प्रतिष्ठा र भोगविलास दिन्छ।',
    },
    requiredPlanets: ['चन्द्र'],
    priorityScore: 78,
  },
  {
    ruleCode: 'YOGA_DURDHARA',
    nameNepali: 'दुर्धरा योग',
    nameSanskrit: 'दुर्धरायोगः',
    category: 'चन्द्र योग',
    descriptionNepali: 'चन्द्रमाको २ औँ र १२ औँ दुवै भावमा सूर्य/राहु/केतु बाहेक अन्य ग्रह हुनु।',
    classicalProof: {
      textNameNepali: 'सारवली',
      textNameSanskrit: 'सारावली',
      chapter: 'अध्याय १३',
      shlokaOrVerse: 'श्लोक १४',
      nepaliMeaningSummary: 'दुर्धरा योगले अत्यधिक वाहन सुख, उदारता, धनधान्य र सम्मान दिन्छ।',
    },
    requiredPlanets: ['चन्द्र'],
    priorityScore: 84,
  },
  {
    ruleCode: 'YOGA_PARIVARTANA_MAHA',
    nameNepali: 'महा परिवर्तन योग',
    nameSanskrit: 'महापरिवर्तनयोगः',
    category: 'राशि परिवर्तन योग',
    descriptionNepali: 'केन्द्र वा त्रिकोण भावका स्वामीहरू बीच एकापसमा राशि परिवर्तन हुनु।',
    classicalProof: {
      textNameNepali: 'फलदीपिका',
      textNameSanskrit: 'फलदीपिका',
      chapter: 'अध्याय ६',
      shlokaOrVerse: 'श्लोक ३२',
      nepaliMeaningSummary: 'शुभ भावका स्वामीहरूको राशि परिवर्तनले व्यक्तिलाई असाधारण वैभव र सफलता दिन्छ।',
    },
    requiredPlanets: [],
    priorityScore: 88,
  },
];

export const DOSHA_RULE_REGISTRY: DoshaRuleDefinition[] = [
  {
    ruleCode: 'DOSHA_MANGAL',
    nameNepali: 'मङ्गल दोष (कुजा दोष)',
    nameSanskrit: 'मङ्गलदोषः / कुजदोषः',
    category: 'मङ्गल दोष',
    descriptionNepali: 'मंगल ग्रह लग्न, चन्द्रमा वा शुक्रबाट १, ४, ७, ८, १२ औँ भावमा स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'देवकेरलम् (चन्द्रकला नाडी)',
      textNameSanskrit: 'देवकेरलम्',
      chapter: 'कुजदोष प्रकरण',
      shlokaOrVerse: 'श्लोक ८४',
      originalSanskritText: 'लग्ने व्यये च पाताले जामित्रे चाष्टमे कुजे। कन्या भर्त्र विनाशाय भर्ता भार्यां विनश्यति॥',
      nepaliMeaningSummary: '१, ४, ७, ८, १२ भावमा मंगल बस्दा वैवाहिक जीवनमा उतारचढाव वा कलह ल्याउन सक्छ, तर अनेकौँ शास्त्रीय अपवादले यो दोष शमित हुन्छ।',
    },
    cancellationRulesSummaryNepali: [
      'मंगल स्वक्षेत्र (मेष/वृश्चिक) वा उच्च (मकर) मा भए दोष भङ्ग हुन्छ।',
      'गुरुको पूर्ण दृष्टि वा युति भए मङ्गल दोष शमित हुन्छ।',
      'सिंह वा धनु लग्नमा मंगल भए दोष लाग्दैन।',
      'द्वितीय भावमा मिथुन/कन्या वा १२ औँ भावमा वृष/तुलाको मंगल भए दोष कट्छ।',
      'वर र कन्या दुवैको कुण्डलीमा मंगल दोष भए दोष साम्य हुन्छ।',
    ],
    remediesNepali: [
      'मंगल शान्ति पूजा तथा हनुमान चालीसा/सुन्दर्काण्ड पाठ',
      'मंगल मन्त्र जप: "ॐ क्रां क्रीं क्रौं सः भौमाय नमः"',
      'लाल वस्तु, तामा, मुसुरो दाल दान',
    ],
  },
  {
    ruleCode: 'DOSHA_KAL_SARP',
    nameNepali: 'कालसर्प योग / दोष',
    nameSanskrit: 'कालसर्पदोषः',
    category: 'कालसर्प दोष',
    descriptionNepali: 'राहु र केतुको एकैतर्फ सबै सात मुख्य ग्रहहरू (सूर्य, चन्द्र, मंगल, बुध, गुरु, शुक्र, शनि) घेरी बस्नु।',
    classicalProof: {
      textNameNepali: 'मानसागरी / नाडी ग्रन्थ',
      textNameSanskrit: 'मानसागरी',
      chapter: 'राहु-केतु विचार',
      shlokaOrVerse: 'श्लोक ४५',
      nepaliMeaningSummary: 'राहु-केतुको अक्षभित्र सबै ग्रह सीमित हुँदा जीवनको पूर्वार्धमा संघर्ष, तर उत्तरार्धमा विशेष आध्यात्मिक वा सामाजिक प्रसिद्धि मिल्न सक्छ।',
    },
    cancellationRulesSummaryNepali: [
      'यदि कुनै एक ग्रह राहु-केतुको घेराबाट बाहिर छ भने आंशिक वा दोषमुक्त हुन्छ।',
      'लग्न वा लग्नेश बलियो भई गुरु केन्द्रमा भए कालसर्पको नकारात्मक प्रभाव न्यून हुन्छ।',
    ],
    remediesNepali: [
      'नागपञ्चमीमा नागपूजा र नागबली / राहु-केतु शान्ति पूजा',
      'महामृत्युञ्जय मन्त्र जप र शिवजीको दूध-जलभिषेक',
    ],
  },
  {
    ruleCode: 'DOSHA_GRAHAN',
    nameNepali: 'ग्रहण दोष',
    nameSanskrit: 'ग्रहणदोषः',
    category: 'ग्रहण दोष',
    descriptionNepali: 'सूर्य वा चन्द्रमासँग राहु वा केतुको नजिकको युति (१० अंशभित्र) वा पूर्ण दृष्टि हुनु।',
    classicalProof: {
      textNameNepali: 'बृहत्पाराशर होराशास्त्र',
      textNameSanskrit: 'बृहत्पाराशरहोराशास्त्रम्',
      chapter: 'अध्याय ३४',
      shlokaOrVerse: 'श्लोक १८',
      nepaliMeaningSummary: 'सूर्यसँग राहु रहँदा आत्मबल/पितृ पक्ष र चन्द्रसँग रहँदा मानसिक सुख तथा मातृ पक्ष प्रभावित हुन सक्छ।',
    },
    cancellationRulesSummaryNepali: [
      'सूर्य/चन्द्र स्वक्षेत्र वा उच्च राशिमा भए ग्रहणको असर न्यून हुन्छ।',
      'शुभ ग्रह गुरुको दृष्टि भए ग्रहण दोष भङ्ग हुन्छ।',
    ],
    remediesNepali: [
      'सूर्य गायत्री / चन्द्र मन्त्र जप र दुग्ध/तामा दान',
      'ग्रहण कालमा जप-तप र राहु-केतु शान्ति',
    ],
  },
  {
    ruleCode: 'DOSHA_GURU_CHANDAL',
    nameNepali: 'गुरु–चाण्डाल दोष',
    nameSanskrit: 'गुरुचाण्डालदोषः',
    category: 'गुरु–चाण्डाल दोष',
    descriptionNepali: 'ज्ञानकारक देवगुरु बृहस्पति र राहु वा केतु एउटै भावमा स्थित हुनु।',
    classicalProof: {
      textNameNepali: 'जातकपारिजात',
      textNameSanskrit: 'जातकपारिजातः',
      chapter: 'अध्याय ८',
      shlokaOrVerse: 'श्लोक २४',
      nepaliMeaningSummary: 'गुरु र राहुको युतिले वैचारिक दुविधा वा धार्मिक प्रश्न उत्पन्न गर्न सक्छ, तर शुभ भावमा विचारशीलता पनि दिन्छ।',
    },
    cancellationRulesSummaryNepali: [
      'गुरु धनु, मीन वा कर्कट राशिमा उच्च/स्वक्षेत्र भए चाण्डाल दोष निष्प्रभावी हुन्छ।',
      'केन्द्र वा त्रिकोणमा गुरु बलियो भए दोष भङ्ग हुन्छ।',
    ],
    remediesNepali: [
      'गुरु मन्त्र जप र विष्णु सहस्रनाम पाठ',
      'पीलो वस्त्र, चनाको दाल, बेसार दान',
    ],
  },
  {
    ruleCode: 'DOSHA_KEMADRUMA',
    nameNepali: 'केमद्रुम दोष',
    nameSanskrit: 'केमद्रुमदोषः',
    category: 'केमद्रुम दोष',
    descriptionNepali: 'चन्द्रमा रहेको भावबाट दोस्रो (२) र बाह्रौँ (१२) दुवै भावमा सूर्य/राहु/केतु बाहेक कुनै पनि ग्रह नहुनु।',
    classicalProof: {
      textNameNepali: 'बृहज्जातक',
      textNameSanskrit: 'बृहज्जातकम्',
      chapter: 'अध्याय १३',
      shlokaOrVerse: 'श्लोक ६',
      originalSanskritText: 'केमद्रुमे भवति दुःखकुल प्रसिद्धः।',
      nepaliMeaningSummary: 'चन्द्रमा एक्लो र निस्सहाय हुँदा केमद्रुम दोष मानिन्छ, जसले मानसिक अकेलापन दिन्छ; तर चन्द्रमा/केन्द्रको शुभ स्थितिले तुरुन्त भङ्ग हुन्छ।',
    },
    cancellationRulesSummaryNepali: [
      'चन्द्रमा वा लग्नबाट केन्द्र (१, ४, ७, १०) मा कुनै ग्रह भए केमद्रुम दोष पूर्ण भङ्ग हुन्छ।',
      'चन्द्रमालाई गुरु वा अन्य शुभ ग्रहले पूर्ण दृष्टि दिए दोष हट्छ।',
      'चन्द्रमा उच्च वा स्वक्षेत्र भए दोष रहँदैन।',
    ],
    remediesNepali: [
      'पूर्णिमा व्रत र चन्द्रमालाई अर्घ्य अर्पण',
      'शिवजीको आराधना र ॐ सोमाय नमः जप',
    ],
  },
];
